
package com.endesa.xmlns.wsdl.sscc.eorder.sitdc501.sitdc501_porttype;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-05-30T12:12:07.405-03:00
 * Generated source version: 3.2.4
 */

@WebFault(name = "MCD_Error", targetNamespace = "http://xmlns.endesa.com/CommonSchemas")
public class CreacionTdCFault extends Exception {

    private com.endesa.xmlns.commonschemas.MCDERROR mcdError;

    public CreacionTdCFault() {
        super();
    }

    public CreacionTdCFault(String message) {
        super(message);
    }

    public CreacionTdCFault(String message, Throwable cause) {
        super(message, cause);
    }

    public CreacionTdCFault(String message, com.endesa.xmlns.commonschemas.MCDERROR mcdError) {
        super(message);
        this.mcdError = mcdError;
    }

    public CreacionTdCFault(String message, com.endesa.xmlns.commonschemas.MCDERROR mcdError, Throwable cause) {
        super(message, cause);
        this.mcdError = mcdError;
    }

    public com.endesa.xmlns.commonschemas.MCDERROR getFaultInfo() {
        return this.mcdError;
    }
}
