
package com.endesa.xmlns.wsdl.sscc.eorder.sitdc501.sitdc501_porttype;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-05-30T12:12:07.240-03:00
 * Generated source version: 3.2.4
 *
 */
public final class SITDC501PortType_SITDC501BindingSOAPHTTP_Client {

    private static final QName SERVICE_NAME = new QName("http://xmlns.endesa.com/wsdl/SSCC/eOrder/SITDC501/SITDC501_PortType", "SITDC501_PortType");

    private SITDC501PortType_SITDC501BindingSOAPHTTP_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = SITDC501PortType_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        SITDC501PortType_Service ss = new SITDC501PortType_Service(wsdlURL, SERVICE_NAME);
        SITDC501PortType port = ss.getSITDC501BindingSOAPHTTP();

        {
        System.out.println("Invoking creacionTdCOperation...");
        com.endesa.xmlns.wsdl.sscc.eorder.sitdc501.mensajes.CreacionTdCRequestType _creacionTdCOperation_request = null;
        try {
            com.endesa.xmlns.wsdl.sscc.eorder.sitdc501.mensajes.CreacionTdCResponseType _creacionTdCOperation__return = port.creacionTdCOperation(_creacionTdCOperation_request);
            System.out.println("creacionTdCOperation.result=" + _creacionTdCOperation__return);

        } catch (CreacionTdCFault e) {
            System.out.println("Expected exception: CreacionTdC_Fault has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
