package com.endesa.xmlns.wsdl.sscc.eorder.sitdc501.sitdc501_porttype;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-05-30T12:12:07.479-03:00
 * Generated source version: 3.2.4
 *
 */
@WebServiceClient(name = "SITDC501_PortType",
                  wsdlLocation = "file:SITDC501Services_gen.wsdl",
                  targetNamespace = "http://xmlns.endesa.com/wsdl/SSCC/eOrder/SITDC501/SITDC501_PortType")
public class SITDC501PortType_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://xmlns.endesa.com/wsdl/SSCC/eOrder/SITDC501/SITDC501_PortType", "SITDC501_PortType");
    public final static QName SITDC501BindingSOAPHTTP = new QName("http://xmlns.endesa.com/wsdl/SSCC/eOrder/SITDC501/SITDC501_PortType", "SITDC501_BindingSOAP_HTTP");
    static {
        URL url = null;
        try {
            url = new URL("file:SITDC501Services_gen.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SITDC501PortType_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:SITDC501Services_gen.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SITDC501PortType_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SITDC501PortType_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SITDC501PortType_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public SITDC501PortType_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public SITDC501PortType_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public SITDC501PortType_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns SITDC501PortType
     */
    @WebEndpoint(name = "SITDC501_BindingSOAP_HTTP")
    public SITDC501PortType getSITDC501BindingSOAPHTTP() {
        return super.getPort(SITDC501BindingSOAPHTTP, SITDC501PortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SITDC501PortType
     */
    @WebEndpoint(name = "SITDC501_BindingSOAP_HTTP")
    public SITDC501PortType getSITDC501BindingSOAPHTTP(WebServiceFeature... features) {
        return super.getPort(SITDC501BindingSOAPHTTP, SITDC501PortType.class, features);
    }

}
